-- AlterTable
ALTER TABLE `ManagedDevice` ADD COLUMN `cpuLoad` INTEGER NULL DEFAULT 0,
    ADD COLUMN `memoryUsage` INTEGER NULL DEFAULT 0,
    ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN `uptime` VARCHAR(191) NULL,
    ADD COLUMN `version` VARCHAR(191) NULL;
