// ==========================================
// Helper Functions: คำนวณ Subnet & IP Pool
// ==========================================
const ipToInt = (ip) => {
  return ip.split('.').reduce((acc, octet) => (acc * 256) + parseInt(octet, 10), 0);
};

const intToIp = (int) => {
  return [
    Math.floor(int / Math.pow(256, 3)) % 256,
    Math.floor(int / Math.pow(256, 2)) % 256,
    Math.floor(int / 256) % 256,
    int % 256
  ].join('.');
};

const calculatePoolRange = (gatewayIP, cidr) => {
  const ipInt = ipToInt(gatewayIP);
  const prefix = parseInt(cidr, 10);
  const totalIps = Math.pow(2, 32 - prefix);
  
  const networkInt = Math.floor(ipInt / totalIps) * totalIps;
  const broadcastInt = networkInt + totalIps - 1;
  
  let poolStartInt = networkInt + 11;
  let poolEndInt = broadcastInt - 11;

  if (poolStartInt > poolEndInt) {
    poolStartInt = networkInt + 1;
    poolEndInt = broadcastInt - 1;
  }

  let poolRange = '';
  if (ipInt >= poolStartInt && ipInt <= poolEndInt) {
    const ranges = [];
    if (poolStartInt <= ipInt - 1) ranges.push(`${intToIp(poolStartInt)}-${intToIp(ipInt - 1)}`);
    if (ipInt + 1 <= poolEndInt) ranges.push(`${intToIp(ipInt + 1)}-${intToIp(poolEndInt)}`);
    poolRange = ranges.join(',');
  } else {
    poolRange = `${intToIp(poolStartInt)}-${intToIp(poolEndInt)}`;
  }

  return {
    networkAddr: `${intToIp(networkInt)}/${cidr}`,
    poolRange: poolRange
  };
};

// ==========================================
// Main Generator Function (For RouterOS v6)
// ==========================================
export const generateMikrotikScriptV6 = (config = {}) => {
  const { 
    selectedModel,
    wanList = [], 
    networks = [], 
    portConfig = {}, 
    pbrConfig = { enabled: false, mappings: {} }, 
    dnsConfig = { servers: ['8.8.8.8', '1.1.1.1'], allowRemoteRequests: true }, 
    wirelessConfig = {},
    circuitId = 'MikroTik-Router', 
    token = '',
    heartbeatUrl = '',
    managementIps = ['10.234.56.0/24'],
    monitorIps = ['1.1.1.1', '8.8.8.8', '208.67.222.222', '9.9.9.9', '8.26.56.26'],
    adminUsers = [{ username: 'ntadmin', password: 'ntadmin', group: 'full' }]
  } = config;

  const bridgeName = "bridge-trunk";
  
  const isProd = import.meta.env?.PROD || false;
  const fetchExtras = isProd ? "check-certificate=no" : "";

  const currentHost = window.location.hostname;
  const currentProtocol = window.location.protocol;
  const isLocal = currentHost === 'localhost' || 
                  currentHost === '127.0.0.1' || 
                  currentHost.startsWith('192.168.') || 
                  currentHost.startsWith('10.') || 
                  currentHost.startsWith('172.');

  const dynamicApiUrl = isLocal 
    ? `http://${currentHost}:3000/api/devices/heartbeat`
    : `${currentProtocol}//${currentHost}/api/devices/heartbeat`;

  // ลำดับความสำคัญ: 1. Manual Set (heartbeatUrl) > 2. .env (VITE_HEARTBEAT_URL) > 3. Auto-Detect (dynamicApiUrl)
  let finalApiUrl = dynamicApiUrl;
  if (heartbeatUrl) {
    const baseUrl = heartbeatUrl.replace(/\/$/, ""); // ตัด / ท้ายสุดออก (ถ้ามี)
    finalApiUrl = baseUrl.endsWith("/api/devices/heartbeat") 
      ? baseUrl 
      : `${baseUrl}/api/devices/heartbeat`;
  } else if (import.meta.env?.VITE_HEARTBEAT_URL) {
    finalApiUrl = import.meta.env.VITE_HEARTBEAT_URL;
  }

  const wanInterfaces = wanList.map(w => w.interface);
  const lanPorts = selectedModel?.ports?.filter(p => !wanInterfaces.includes(p.name) && p.type !== 'WLAN') || [];

  // 🟢 หาพอร์ต Ethernet สุดท้ายไว้เป็น Fallback Management
  const etherPorts = lanPorts.filter(p => p.type === 'ETHER' || p.name.toLowerCase().startsWith('ether'));
  const fallbackPortName = etherPorts.length > 0 ? etherPorts[etherPorts.length - 1].name : null;

  const safeMonitorIps = (monitorIps && monitorIps.length >= 5) 
    ? monitorIps 
    : ['1.1.1.1', '8.8.8.8', '208.67.222.222', '9.9.9.9', '8.26.56.26'];

  try {
    let script = `################################################\n`;
    script += `# Generated by Mikrotik Config Wizard (For RouterOS v6)\n`;
    script += `# Environment: ${isProd ? 'Production' : 'Development'}\n`;
    script += `# Date: ${new Date().toLocaleString()}\n`;
    script += `# Identity: ${circuitId}\n`;
    script += `################################################\n\n`;

    // --- 1. INITIAL SETUP ---
    script += `/system identity set name="${circuitId}"\n`;
    script += `/interface bridge add name=${bridgeName} comment="Main LAN Bridge" vlan-filtering=no\n`;

    script += `\n# --- Interface Lists ---\n`;
    script += `/interface list add name=WAN\n`;
    script += `/interface list add name=LAN\n`;
    script += `/interface list member add interface=${bridgeName} list=LAN\n`;
    lanPorts.forEach(port => {
      script += `:do { /interface list member add interface=${port.name} list=LAN } on-error={}\n`;
    });
    script += `\n`;

    script += `/system clock set time-zone-name=Asia/Bangkok\n`;
    
    // 🟢 v6 Fix: ใช้ SNTP เป็น fallback และใช้ IP ตรงๆ เพื่อลดปัญหา DNS Resolution ก่อนเชื่อมต่อเน็ตได้
    script += `:do { /system ntp client set enabled=yes primary-ntp=216.239.35.0 secondary-ntp=216.239.35.4 } on-error={ /system sntp client set enabled=yes primary-ntp=216.239.35.0 secondary-ntp=216.239.35.4 }\n`;

    script += `\n# --- Admin Users ---\n`;
    adminUsers.forEach(admin => {
      script += `:do { /user add name="${admin.username}" group="${admin.group}" password="${admin.password}" comment="Provisioned by Central API" } on-error={ /user set [find name="${admin.username}"] group="${admin.group}" password="${admin.password}" }\n`;
    });
    
    const excludeUsers = adminUsers.map(u => `name!="${u.username}"`).join(" and ");
    if (excludeUsers) {
        script += `/user remove [find ${excludeUsers}]\n`;
    }

    script += `/ip service set telnet disabled=yes\n`;
    script += `/ip service set ftp disabled=yes\n`;
    script += `/ip service set www disabled=yes\n`;
    script += `/ip service set ssh disabled=yes\n`;
    script += `/ip service set api disabled=yes\n`;
    script += `/ip service set api-ssl disabled=yes\n`;
    script += `/ip service set winbox disabled=no\n`;

    script += `/ip neighbor discovery-settings set discover-interface-list=LAN\n`;
    script += `/tool mac-server set allowed-interface-list=LAN\n`;
    script += `/tool mac-server mac-winbox set allowed-interface-list=LAN\n`;
    script += `/tool mac-server ping set enabled=no\n`;

    // --- 2. ADDRESS LISTS ---
    script += `\n# --- Address Lists ---\n`;
    script += `/ip firewall address-list remove [find list="Local_Networks"]\n`;
    script += `/ip firewall address-list remove [find list="management"]\n`;
    
    const uniqueMgmtIps = [...new Set(managementIps.map(ip => ip.trim()).filter(ip => ip !== ''))];
    uniqueMgmtIps.forEach(ip => {
        script += `/ip firewall address-list add list=management address=${ip} comment="Central Management"\n`;
    });
    
    networks.forEach(net => {
       script += `/ip firewall address-list add list=Local_Networks address=${net.ip} comment="${net.name}"\n`;
    });

    // --- 3. WAN SETUP ---
    script += `\n# --- WAN Interface Setup ---\n`;

    wanList.forEach((wan, index) => {
      const i = index + 1;
      const wanName = `wan${i}-${wan.interface}`;
      
      const monitorIp = safeMonitorIps[index % safeMonitorIps.length];
      wan.monitorIp = monitorIp;

      script += `:do { /interface set [find default-name=${wan.interface}] name=${wanName} comment="WAN ${i}" } on-error={ :log error "WAN Interface ${wan.interface} not found" }\n`;

      let actualGw = '';
      if (wan.type === 'pppoe') {
        // 🟢 v6 RSC Ironclad Fix: ใช้ \22 แทนเครื่องหมายคำพูดข้างในสคริปต์ เพื่อป้องกันปัญหาการ Import ไฟล์ .rsc ล้มเหลว
        // และใช้ \$ เพื่อป้องกันการตีความเป็นตัวแปรในขณะ Import
        script += `/ppp profile add name="profile_wan${i}" on-up=":delay 5; :local gw \\$\\22remote-address\\22; /ip route set [find comment=\\22Host Route for WAN${i}\\22] gateway=\\$gw; :log info \\22Wizard: Updated WAN${i} gateway to \$gw\\22"\n`;
        script += `/interface pppoe-client add name="pppoe-out${i}" interface=${wanName} user="${wan.username}" password="${wan.password}" profile="profile_wan${i}" disabled=no add-default-route=no use-peer-dns=yes\n`;
        script += `/interface list member add interface=pppoe-out${i} list=WAN\n`;
        actualGw = `pppoe-out${i}`;
      } else {
        script += `/ip address add address=${wan.ipAddress} interface=${wanName} comment="Static WAN"\n`;
        script += `/interface list member add interface=${wanName} list=WAN\n`;
        actualGw = wan.gateway;
      }
      wan.actualGw = actualGw; 
    });

    // --- 4. Main Routing Table ---
    script += `\n# --- Main Routing Table (Recursive Logic) ---\n`;
    wanList.forEach((wan, index) => {
      const i = index + 1;
      // 🟢 v6 Verified Fix: สร้าง Host Route ด้วยชื่อ Interface (Profile Script จะเป็นตัวอัปเดตเป็น IP ภายหลัง)
      script += `/ip route add dst-address=${wan.monitorIp}/32 gateway=${wan.actualGw} scope=10 comment="Host Route for WAN${i}"\n`;
      script += `/ip route add dst-address=0.0.0.0/0 gateway=${wan.monitorIp} distance=${i} check-gateway=ping target-scope=10 comment="Main Recursive Default Route WAN${i}"\n`;
    });

    // --- 5. LAN & VLAN SETUP ---
    script += `\n# --- LAN & VLAN Interfaces ---\n`;
    networks.forEach(net => {
      const vlanInterface = `${net.name}-v${net.vlanId}`;
      script += `/interface vlan add interface=${bridgeName} name=${vlanInterface} vlan-id=${net.vlanId}\n`;
      script += `/interface list member add interface=${vlanInterface} list=LAN\n`;
      script += `/ip address add address=${net.ip} interface=${vlanInterface} comment="${net.name} Gateway"\n`;
      
      const [gatewayIP, cidr] = net.ip.split('/');
      
      const { networkAddr, poolRange } = calculatePoolRange(gatewayIP, cidr);
      const poolName = `pool-${net.name}`;

      const clientDnsServers = dnsConfig.allowRemoteRequests ? gatewayIP : dnsConfig.servers.join(',');

      if (net.dhcp || net.hotspot) {
        script += `/ip pool add name="${poolName}" ranges=${poolRange}\n`;
        script += `/ip dhcp-server add name="dhcp-${net.name}" interface=${vlanInterface} address-pool="${poolName}" disabled=no lease-time=1d\n`;
        script += `/ip dhcp-server network add address=${networkAddr} gateway=${gatewayIP} dns-server=${clientDnsServers}\n`;
      }

      if (net.hotspot) {
        script += `\n  # --- Hotspot Server: ${net.name} ---\n`;
        script += `  /ip hotspot profile add name="hsprof-${net.name}" hotspot-address=${gatewayIP} dns-name="login.wifi.local" login-by=mac-cookie,http-pap\n`;
        script += `  /ip hotspot add name="hs-${net.name}" interface=${vlanInterface} address-pool="${poolName}" profile="hsprof-${net.name}" disabled=no\n\n`;
      }
    });

    // --- 6. PORT ASSIGNMENT ---
    if (lanPorts.length > 0) {
      script += `\n# --- Port Assignment ---\n`;
      const defaultPvid = networks.length > 0 ? Number(networks[0].vlanId) : 1;

      lanPorts.forEach(port => {
         const isFallback = port.name === fallbackPortName;
         
         // 🔴 [ROS v6/v7 FIX] Skip fallback port from bridge to prevent disconnect when vlan-filtering is enabled
         if (isFallback) {
            script += `# Port ${port.name} is reserved for Rescue/Management (Not in Bridge)\n`;
            script += `/ip address add address=192.168.88.1/24 interface=${port.name} comment="Rescue IP - Always use this if locked out"\n`;
            return;
         }

         const pConfig = portConfig[port.name] || { mode: 'access', pvid: defaultPvid, nativeVlan: 1, allowed: [] };
         const portPvid = pConfig.mode === 'access' ? (pConfig.pvid || defaultPvid) : (pConfig.nativeVlan || 1);
         const commentStr = `LAN Port (${pConfig.mode})`;

         script += `:do { /interface bridge port add bridge=${bridgeName} interface=${port.name} pvid=${portPvid} comment="${commentStr}" } on-error={ :log warning "Wizard: Port ${port.name} not found" }\n`;
      });
    }

    // --- 7. WIRELESS CONFIGURATION ---
    if (wirelessConfig && Object.keys(wirelessConfig).length > 0) {
      script += `\n# --- Wireless Setup ---\n`;
      Object.entries(wirelessConfig).forEach(([portName, config]) => {
        if (!config.ssid) return;
        const secProfileName = `sec_profile_${portName}`;
        script += `/interface wireless security-profiles\n`;
        if (config.security === 'none') {
          script += `add name="${secProfileName}" mode=none\n`;
        } else {
          // 🟢 v6 Fix: บังคับใช้แค่ wpa2-psk เพื่อหลีกเลี่ยง error ในรุ่นเก่า
          script += `add name="${secProfileName}" mode=dynamic-keys authentication-types="wpa2-psk" wpa2-pre-shared-key="${config.password}"\n`;
        }
        script += `/interface wireless\n`;
        script += `:do { set [ find default-name="${portName}" ] mode=ap-bridge ssid="${config.ssid}" security-profile="${secProfileName}" disabled=no ${config.band ? `band="${config.band}"` : ''} } on-error={}\n`;
        script += `:do { /interface bridge port add bridge=${bridgeName} interface=${portName} pvid=1 comment="WLAN Port" } on-error={}\n`;
      });
    }

    // --- 8. BRIDGE VLAN FILTERING TABLE ---
    if (networks.length > 0) {
      script += `\n# --- Bridge VLAN Table ---\n`;
      script += `/interface bridge vlan\n`;

      networks.forEach(net => {
        const vlanId = net.vlanId;
        const taggedPorts = [bridgeName];

        lanPorts.forEach(port => {
          const pConfig = portConfig[port.name];
          if (pConfig && pConfig.mode === 'trunk' && pConfig.allowed && pConfig.allowed.includes(vlanId)) {
            taggedPorts.push(port.name);
          }
        });

        script += `add bridge=${bridgeName} tagged=${taggedPorts.join(',')} vlan-ids=${vlanId}\n`;
      });
    }

    // --- 9. DNS & FIREWALL ---
    script += `\n# --- DNS & Firewall ---\n`;
    script += `/ip dns set servers=${dnsConfig.servers.join(',')} allow-remote-requests=${dnsConfig.allowRemoteRequests ? 'yes' : 'no'}\n`;
    script += `/ip firewall nat add chain=srcnat action=masquerade out-interface-list=WAN comment="WAN Masquerade"\n`;

    script += `\n/ip firewall filter\n`;
    script += `# Input Chain (Protect Router)\n`;
    script += `add action=drop chain=input comment="Drop Invalid" connection-state=invalid\n`;
    script += `add action=accept chain=input comment="Established" connection-state=established,related\n`;
    script += `add action=accept chain=input comment="Winbox & API" dst-port=8291 protocol=tcp src-address-list=management\n`;
    script += `add action=accept chain=input comment="ICMP" protocol=icmp\n`;
    script += `add action=accept chain=input comment="DNS UDP" dst-port=53 protocol=udp src-address-list=Local_Networks\n`;
    script += `add action=accept chain=input comment="DNS TCP" dst-port=53 protocol=tcp src-address-list=Local_Networks\n`;
    script += `add action=drop chain=input comment="Drop All Else"\n`;
    
    script += `# Forward Chain (Protect LAN from WAN)\n`;
    script += `add action=fasttrack-connection chain=forward comment="FastTrack" connection-state=established,related\n`;
    script += `add action=accept chain=forward comment="Established, Related" connection-state=established,related\n`;
    script += `add action=drop chain=forward comment="Drop Invalid" connection-state=invalid\n`;
    script += `add action=drop chain=forward comment="Drop incoming from WAN not DST-NATed" connection-nat-state=!dstnat connection-state=new in-interface-list=WAN\n`;

    // --- 10. MANGLE & PBR ---
    script += `\n# --- Policy Based Routing & Mangle ---\n`;
    script += `/ip firewall mangle\n`;
    
    wanList.forEach((wan, index) => {
        const i = index + 1;
        if (wan.type === 'pppoe') {
            script += `add action=change-mss chain=forward comment="Clamp MTU for PPPoE${i}" new-mss=clamp-to-pmtu out-interface=pppoe-out${i} passthrough=yes protocol=tcp tcp-flags=syn tcp-mss=1-65535\n`;
        }
    });

    if (pbrConfig.enabled) {
      script += `\n/ip firewall mangle\n`;
      script += `add chain=prerouting src-address-list=Local_Networks dst-address-list=Local_Networks action=accept comment="Bypass PBR for Local Traffic"\n`;
      
      networks.forEach(net => {
        const selectedWanId = (pbrConfig.mappings && pbrConfig.mappings[net.id]) || (wanList.length > 0 ? wanList[0].id : null);
        if (selectedWanId) {
           const foundIndex = wanList.findIndex(w => String(w.id) === String(selectedWanId));
           if (foundIndex !== -1) {
              const wanNum = foundIndex + 1;
              const [gw, cidr] = net.ip.split('/');
              const { networkAddr } = calculatePoolRange(gw, cidr);
              
              // 🟢 v6: Standard PBR marking
              script += `add chain=prerouting src-address=${networkAddr} dst-address-list=!Local_Networks action=mark-routing new-routing-mark=to_wan${wanNum} passthrough=no comment="Route ${net.name} -> WAN${wanNum}"\n`;
           }
        }
      });
      
      script += `\n/ip route\n`;
      wanList.forEach((wan, index) => {
          const i = index + 1;
          const markName = `to_wan${i}`;
          
          // 🟢 v6 Fix: PBR Route ชี้ไปที่ Monitor IP (target-scope=10 เพื่อ Resolve Host Route ที่ใช้ IP)
          script += `add dst-address=0.0.0.0/0 gateway=${wan.monitorIp} distance=1 routing-mark=${markName} check-gateway=ping target-scope=10 comment="PBR Primary Default Route WAN${i}"\n`;
          
          let backupDistance = 2;
          wanList.forEach((backupWan, bIdx) => {
              if (index !== bIdx) {
                  const bNum = bIdx + 1;
                  script += `add dst-address=0.0.0.0/0 gateway=${backupWan.monitorIp} distance=${backupDistance} routing-mark=${markName} check-gateway=ping target-scope=10 comment="PBR Backup to WAN${bNum}"\n`;
                  backupDistance++;
              }
          });
      });
    }

    // --- 11. ENABLE VLAN FILTERING ---
    script += `\n################################################\n`;
    script += `# Apply VLAN Filtering\n`;
    script += `################################################\n`;
    script += `/interface bridge set ${bridgeName} vlan-filtering=yes\n`;

    if (config.isStandalone) {
        script += `\n################################################\n`;
        script += `# Config Builder Mode: Heartbeat Disabled\n`;
        script += `################################################\n`;
        return script;
    }

    // --- 12. START HEARTBEAT SCRIPT ---
    script += `\n################################################\n`;
    script += `# Start Heartbeat Monitoring (API)\n`;
    script += `################################################\n`;
    
    script += `/system script remove [find name="heartbeat-script"]\n`;
    script += `/system script add name="heartbeat-script" source={\n`;
    script += `  :local serverUrl "${finalApiUrl}";\n`;
    script += `  :local apiToken "${token}";\n`;
    script += `  :local cpuLoad [/system resource get cpu-load];\n`;
    script += `  :local freeMem [/system resource get free-memory];\n`;
    script += `  :local totalMem [/system resource get total-memory];\n`;
    script += `  :local usedMem ($totalMem - $freeMem);\n`;
    script += `  :local memPercent (($usedMem * 100) / $totalMem);\n`;
    script += `  :local uptime [/system resource get uptime];\n`;
    script += `  :local version [/system resource get version];\n`;
    script += `  :local boardName [/system resource get board-name];\n`;
    script += `  :local freeHdd [/system resource get free-hdd-space];\n`;
    script += `  :local totalHdd [/system resource get total-hdd-space];\n`;
    script += `  :local hddPercent 0;\n`;
    script += `  :if ($totalHdd > 0) do={ :set hddPercent (((($totalHdd - $freeHdd) * 100) / $totalHdd)) };\n`;
    script += `  :local temp "N/A";\n`;
    script += `  :do { :set temp [/system health get temperature] } on-error={};\n`;
    
    script += `  :local latency "timeout";\n`;
    script += `  :do {\n`;
    script += `    :if ([:ping 8.8.8.8 count=3] > 0) do={ :set latency "N/A" }\n`;
    script += `  } on-error={};\n`;
    
    script += `  :local ddnsName "N/A";\n`;
    script += `  :do { :set ddnsName [/ip cloud get dns-name] } on-error={};\n`;
    script += `  :local payload "{\\"cpu\\":\\"$cpuLoad\\", \\"ram\\":\\"$memPercent\\", \\"storage\\":\\"$hddPercent\\", \\"temp\\":\\"$temp\\", \\"latency\\":\\"$latency\\", \\"ddnsName\\":\\"$ddnsName\\", \\"uptime\\":\\"$uptime\\", \\"version\\":\\"$version\\", \\"boardName\\":\\"$boardName\\"}";\n`;    
    
    // 🌟 v6: ไม่ใช้ :toarray เพราะอาจทำให้เกิดปัญหากับบางเวอร์ชั่น ให้ใช้สตริงต่อกันตรงๆ
    script += `  :local headers "Authorization: Bearer $apiToken,Content-Type: application/json";\n`;
    script += `  :do {\n`;
    script += `    /tool fetch url=$serverUrl http-method=post http-header-field=$headers http-data=$payload keep-result=no ${fetchExtras};\n`;
    script += `  } on-error={ :log error "Failed to send Heartbeat" }\n`;
    script += `}\n`;

    script += `/system scheduler remove [find name="heartbeat-schedule"]\n`;
    script += `/system scheduler add name="heartbeat-schedule" interval=30s on-event="heartbeat-script"\n\n`;

    return script;

  } catch (error) {
    console.error("Generator Error:", error);
    return `# Error generating script: ${error.message}`;
  }
};
