export const generateMikrotikScript = (config = {}) => {
  const { 
    selectedModel,
    wanList = [], 
    networks = [], 
    portConfig = {}, 
    pbrConfig = { enabled: false, mappings: {} }, 
    dnsConfig = { servers: ['8.8.8.8', '1.1.1.1'], allowRemoteRequests: true }, 
    wirelessConfig = {}, // ✅ 1. รับค่า wirelessConfig เข้ามา
    circuitId = 'MikroTik-Router', 
    token = '', 
    apiHost = '10.0.0.100' // ค่า Default
  } = config;

  const bridgeName = "bridge-trunk";
  
  // หา LAN Ports
  const wanInterfaces = wanList.map(w => w.interface);
  const lanPorts = selectedModel?.ports.filter(p => !wanInterfaces.includes(p.name) && p.type !== 'WLAN') || []; // ✅ ยกเว้นพอร์ต WLAN ไม่ให้ไปเข้า Bridge แบบสายแลนปกติ

  try {
    let script = `################################################\n`;
    script += `# Generated by Mikrotik Config Wizard\n`;
    script += `# Date: ${new Date().toLocaleString()}\n`;
    script += `# Identity: ${circuitId}\n`;
    script += `################################################\n\n`;

    // --- 1. INITIAL SETUP ---
    script += `/system identity set name="${circuitId}"\n`;
    script += `/interface bridge add name=${bridgeName} comment="Main LAN Bridge"\n`;

    // --- 2. ADDRESS LISTS (สำคัญสำหรับ Firewall/NAT) ---
    script += `\n# --- Address Lists ---\n`;
    script += `/ip firewall address-list remove [find list="Local_Networks"]\n`;
    networks.forEach(net => {
       script += `/ip firewall address-list add list=Local_Networks address=${net.ip} comment="${net.name}"\n`;
    });

    // --- 3. WAN SETUP ---
    script += `\n# --- WAN Interface Setup ---\n`;
    wanList.forEach((wan, index) => {
      const i = index + 1;
      const wanName = `wan${i}-${wan.interface}`;
      
      // Rename Interface
      script += `/interface set [find default-name=${wan.interface}] name=${wanName} comment="WAN ${i}"\n`;

      // Config IP / PPPoE
      if (wan.type === 'pppoe') {
        script += `/interface pppoe-client add name="pppoe-out${i}" interface=${wanName} user="${wan.username}" password="${wan.password}" disabled=no add-default-route=yes use-peer-dns=yes\n`;
        // Interface List Member
        script += `/interface list member add interface=pppoe-out${i} list=WAN\n`;
      } else {
        script += `/ip address add address=${wan.ipAddress} interface=${wanName} comment="Static WAN"\n`;
        script += `/ip route add gateway=${wan.gateway} distance=${i} comment="Default Route WAN${i}"\n`;
        // Interface List Member
        script += `/interface list member add interface=${wanName} list=WAN\n`;
      }
    });

    // สร้าง Interface List LAN/WAN
    script += `/interface list add name=WAN\n`;
    script += `/interface list add name=LAN\n`;
    script += `/interface list member add interface=${bridgeName} list=LAN\n`;

    // --- 4. LAN & VLAN SETUP ---
    script += `\n# --- LAN & VLAN Setup ---\n`;
    networks.forEach(net => {
      const vlanInterface = `${net.name}-v${net.vlanId}`;
      script += `/interface vlan add interface=${bridgeName} name=${vlanInterface} vlan-id=${net.vlanId}\n`;
      script += `/ip address add address=${net.ip} interface=${vlanInterface} comment="${net.name} Gateway"\n`;
      
      if (net.dhcp) {
        const networkAddr = net.ip.replace('1/24', '0/24');
        const gatewayIP = net.ip.split('/')[0];
        // คำนวณ Range IP ง่ายๆ (x.x.x.10 - x.x.x.254)
        const ipParts = gatewayIP.split('.');
        ipParts.pop(); 
        const poolRange = `${ipParts.join('.')}.10-${ipParts.join('.')}.254`;

        script += `/ip pool add name="pool-${net.name}" ranges=${poolRange}\n`;
        script += `/ip dhcp-server add name="dhcp-${net.name}" interface=${vlanInterface} address-pool="pool-${net.name}" disabled=no lease-time=1d\n`;
        script += `/ip dhcp-server network add address=${networkAddr} gateway=${gatewayIP} dns-server=${dnsConfig.servers.join(',')}\n`;
      }
    });

    // --- 5. PORT ASSIGNMENT (BRIDGE) ---
    script += `\n# --- Bridge Port Assignment ---\n`;
    // Add All LAN ports to Bridge
    lanPorts.forEach(port => {
       script += `/interface bridge port add bridge=${bridgeName} interface=${port.name} comment="LAN Port"\n`;
    });

    // --- 6. WIRELESS CONFIGURATION (NEW! 📡) ---
    // ✅ 2. เพิ่มส่วนจัดการตั้งค่า Wi-Fi ตามที่กำหนดในหน้าเว็บ
    if (wirelessConfig && Object.keys(wirelessConfig).length > 0) {
      script += `\n# --- Wireless Setup ---\n`;
      Object.entries(wirelessConfig).forEach(([portName, config]) => {
        if (!config.ssid) return; // ข้ามถ้าไม่มีการตั้งชื่อ SSID

        const secProfileName = `sec_profile_${portName}`;
        const isNoPassword = config.security === 'none';

        // 6.1 สร้าง Security Profile (รหัสผ่าน Wi-Fi)
        script += `/interface wireless security-profiles\n`;
        if (isNoPassword) {
          script += `add name="${secProfileName}" mode=none\n`;
        } else {
          // ถ้าเลือก WPA2 หรือ WPA3
          const authTypes = config.security === 'wpa2-wpa3-psk' 
            ? 'wpa2-psk,wpa3-psk' 
            : 'wpa2-psk';

          script += `add name="${secProfileName}" mode=dynamic-keys authentication-types="${authTypes}" `;
          script += `wpa2-pre-shared-key="${config.password}" `;
          if (config.security === 'wpa2-wpa3-psk') {
            script += `wpa3-pre-shared-key="${config.password}" `;
          }
          script += `\n`;
        }

        // 6.2 ผูก Profile กับ Interface เปิดใช้งาน และเอาเข้า Bridge
        script += `/interface wireless\n`;
        script += `set [ find default-name="${portName}" ] mode=ap-bridge ssid="${config.ssid}" `;
        script += `security-profile="${secProfileName}" disabled=no `;
        
        // ถ้ามีการกำหนดคลื่นความถี่
        if (config.band) {
          script += `band="${config.band}" `;
        }
        script += `\n`;

        // นำพอร์ต Wi-Fi เข้า Bridge ด้วย เพื่อให้รับ IP จาก DHCP ได้
        script += `/interface bridge port add bridge=${bridgeName} interface=${portName} comment="WLAN Port"\n`;
      });
    }

    // --- 7. DNS & FIREWALL BASIC ---
    script += `\n# --- DNS & Firewall ---\n`;
    script += `/ip dns set servers=${dnsConfig.servers.join(',')} allow-remote-requests=${dnsConfig.allowRemoteRequests ? 'yes' : 'no'}\n`;
    
    // NAT (Masquerade)
    script += `/ip firewall nat add chain=srcnat action=masquerade out-interface-list=WAN comment="WAN Masquerade"\n`;

    // Basic Filter Rules (ความปลอดภัยพื้นฐาน)
    script += `/ip firewall filter\n`;
    script += `add chain=input action=accept connection-state=established,related comment="Accept Established"\n`;
    script += `add chain=input action=accept protocol=icmp comment="Allow Ping"\n`;
    script += `add chain=input action=accept in-interface-list=LAN comment="Allow LAN Input"\n`;
    script += `add chain=input action=drop in-interface-list=WAN comment="Drop WAN Input" disabled=yes\n`; // Disabled ไว้ก่อน กันพลาดเข้า Winbox ไม่ได้
    script += `add chain=forward action=accept connection-state=established,related comment="Accept Forward Established"\n`;
    
    // --- 8. MANGLE & PBR (Policy Based Routing) ---
    if (pbrConfig.enabled) {
      script += `\n# --- Policy Based Routing (PBR) ---\n`;
      script += `/ip firewall mangle\n`;
      
      // Bypass Local Traffic (Inter-VLAN)
      script += `add chain=prerouting src-address-list=Local_Networks dst-address-list=Local_Networks action=accept comment="Bypass PBR for Local Traffic"\n`;

      networks.forEach(net => {
        const selectedWanId = pbrConfig.mappings[net.id];
        if (selectedWanId) {
           const wanIndex = wanList.findIndex(w => String(w.id) === String(selectedWanId)) + 1;
           if (wanIndex > 0) {
              const networkAddr = net.ip.replace('1/24', '0/24');
              script += `add chain=prerouting src-address=${networkAddr} dst-address-list=!Local_Networks action=mark-routing new-routing-mark=to_wan${wanIndex} passthrough=yes comment="Route ${net.name} -> WAN${wanIndex}"\n`;
           }
        }
      });

      // Default Routes for Routing Marks
      wanList.forEach((wan, index) => {
          const i = index + 1;
          const gw = wan.type === 'pppoe' ? `pppoe-out${i}` : wan.gateway;
          script += `/ip route add distance=1 gateway=${gw} routing-mark=to_wan${i} comment="Route for WAN${i}"\n`;
      });
    }

    // --- 9. SYSTEM MONITORING & HEARTBEAT ---
    script += `\n################################################\n`;
    script += `# Monitoring & Heartbeat System (Auto-Update)\n`;
    script += `################################################\n`;
    
    script += `/system script remove [find name="heartbeat-script"]\n`;
    script += `/system script add name="heartbeat-script" source={\n`;
    script += `  :local serverUrl "http://${apiHost}:3000/api/devices/heartbeat";\n`; 
    script += `  :local apiToken "${token}";\n`;
    script += `  :local cpuLoad [/system resource get cpu-load];\n`;
    script += `  :local freeMem [/system resource get free-memory];\n`;
    script += `  :local totalMem [/system resource get total-memory];\n`;
    script += `  :local usedMem ($totalMem - $freeMem);\n`;
    script += `  :local memPercent (($usedMem * 100) / $totalMem);\n`;
    script += `  :local uptime [/system resource get uptime];\n`;
    script += `  :local version [/system resource get version];\n`;
    
    script += `  :local payload "{\\"cpu\\":\\"$cpuLoad\\", \\"ram\\":\\"$memPercent\\", \\"uptime\\":\\"$uptime\\", \\"version\\":\\"$version\\"}";\n`;
    
    script += `  :do {\n`;
    script += `    /tool fetch mode=http url=$serverUrl http-method=post http-header-field="Authorization: Bearer $apiToken,Content-Type: application/json" http-data=$payload keep-result=no;\n`;
    script += `    :log info "Heartbeat sent: CPU $cpuLoad%, RAM $memPercent%";\n`;
    script += `  } on-error={\n`;
    script += `    :log error "Failed to send Heartbeat to Server ($serverUrl)";\n`;
    script += `  }\n`;
    script += `}\n`;

    script += `/system scheduler remove [find name="heartbeat-schedule"]\n`;
    script += `/system scheduler add name="heartbeat-schedule" interval=30s on-event="heartbeat-script"\n`;

    return script;

  } catch (error) {
    console.error("Generator Error:", error);
    return `# Error generating script: ${error.message}`;
  }
};