export const generateMikrotikScript = (config = {}) => {
  const { 
    selectedModel,
    wanList = [], 
    networks = [], 
    portConfig = {}, 
    pbrConfig = { enabled: false, mappings: {} }, 
    dnsConfig = { servers: ['8.8.8.8', '1.1.1.1'], allowRemoteRequests: true }, 
    wirelessConfig = {},
    circuitId = 'MikroTik-Router', 
    token = '', 
    apiHost = '10.0.0.100' // จะถูกแทนที่ด้วย Logic ด้านล่าง
  } = config;

  const bridgeName = "bridge-trunk";
  
  // ✅ ตรวจสอบสภาพแวดล้อม (Local vs Production)
  const isProd = import.meta.env.PROD;
  const finalApiUrl = isProd 
    ? "https://mikrotik.ntplcnst.com/api/devices/heartbeat" 
    : `http://${window.location.hostname}:3000/api/devices/heartbeat`;

  // ✅ กำหนด Parameter เสริมสำหรับ HTTPS
  const fetchExtras = isProd ? "check-certificate=no" : "";

  // หา LAN Ports
  const wanInterfaces = wanList.map(w => w.interface);
  const lanPorts = selectedModel?.ports.filter(p => !wanInterfaces.includes(p.name) && p.type !== 'WLAN') || [];

  try {
    let script = `################################################\n`;
    script += `# Generated by Mikrotik Config Wizard\n`;
    script += `# Environment: ${isProd ? 'Production' : 'Development'}\n`;
    script += `# Date: ${new Date().toLocaleString()}\n`;
    script += `# Identity: ${circuitId}\n`;
    script += `################################################\n\n`;

    // --- 1. INITIAL SETUP ---
    script += `/system identity set name="${circuitId}"\n`;
    script += `/interface bridge add name=${bridgeName} comment="Main LAN Bridge"\n`;

    // --- 2. ADDRESS LISTS ---
    script += `\n# --- Address Lists ---\n`;
    script += `/ip firewall address-list remove [find list="Local_Networks"]\n`;
    networks.forEach(net => {
       script += `/ip firewall address-list add list=Local_Networks address=${net.ip} comment="${net.name}"\n`;
    });

    // --- 3. WAN SETUP ---
    script += `\n# --- WAN Interface Setup ---\n`;
    wanList.forEach((wan, index) => {
      const i = index + 1;
      const wanName = `wan${i}-${wan.interface}`;
      script += `/interface set [find default-name=${wan.interface}] name=${wanName} comment="WAN ${i}"\n`;

      if (wan.type === 'pppoe') {
        script += `/interface pppoe-client add name="pppoe-out${i}" interface=${wanName} user="${wan.username}" password="${wan.password}" disabled=no add-default-route=yes use-peer-dns=yes\n`;
        script += `/interface list member add interface=pppoe-out${i} list=WAN\n`;
      } else {
        script += `/ip address add address=${wan.ipAddress} interface=${wanName} comment="Static WAN"\n`;
        script += `/ip route add gateway=${wan.gateway} distance=${i} comment="Default Route WAN${i}"\n`;
        script += `/interface list member add interface=${wanName} list=WAN\n`;
      }
    });

    script += `/interface list add name=WAN\n`;
    script += `/interface list add name=LAN\n`;
    script += `/interface list member add interface=${bridgeName} list=LAN\n`;

    // --- 4. LAN & VLAN SETUP ---
    script += `\n# --- LAN & VLAN Setup ---\n`;
    networks.forEach(net => {
      const vlanInterface = `${net.name}-v${net.vlanId}`;
      script += `/interface vlan add interface=${bridgeName} name=${vlanInterface} vlan-id=${net.vlanId}\n`;
      script += `/ip address add address=${net.ip} interface=${vlanInterface} comment="${net.name} Gateway"\n`;
      
      const gatewayIP = net.ip.split('/')[0];
      const poolName = `pool-${net.name}`;

      if (net.dhcp) {
        const networkAddr = net.ip.replace('1/24', '0/24');
        const ipParts = gatewayIP.split('.');
        ipParts.pop(); 
        const poolRange = `${ipParts.join('.')}.10-${ipParts.join('.')}.254`;

        script += `/ip pool add name="${poolName}" ranges=${poolRange}\n`;
        script += `/ip dhcp-server add name="dhcp-${net.name}" interface=${vlanInterface} address-pool="${poolName}" disabled=no lease-time=1d\n`;
        script += `/ip dhcp-server network add address=${networkAddr} gateway=${gatewayIP} dns-server=${dnsConfig.servers.join(',')}\n`;
      }

      if (net.hotspot) {
        script += `\n  # --- Hotspot Server: ${net.name} ---\n`;
        script += `  /ip hotspot profile add name="hsprof-${net.name}" hotspot-address=${gatewayIP} dns-name="${net.name.toLowerCase()}.hotspot.local" login-by=cookie,http-chap,http-pap\n`;
        script += `  /ip hotspot add name="hs-${net.name}" interface=${vlanInterface} address-pool="${poolName}" profile="hsprof-${net.name}" disabled=no\n`;
        script += `  /ip hotspot user add name="admin" password="password" server="hs-${net.name}" comment="Default Hotspot Admin"\n\n`;
      }
    });

    // --- 5. PORT ASSIGNMENT ---
    lanPorts.forEach(port => {
       script += `/interface bridge port add bridge=${bridgeName} interface=${port.name} comment="LAN Port"\n`;
    });

    // --- 6. WIRELESS CONFIGURATION ---
    if (wirelessConfig && Object.keys(wirelessConfig).length > 0) {
      script += `\n# --- Wireless Setup ---\n`;
      Object.entries(wirelessConfig).forEach(([portName, config]) => {
        if (!config.ssid) return;
        const secProfileName = `sec_profile_${portName}`;
        script += `/interface wireless security-profiles\n`;
        if (config.security === 'none') {
          script += `add name="${secProfileName}" mode=none\n`;
        } else {
          const authTypes = config.security === 'wpa2-wpa3-psk' ? 'wpa2-psk,wpa3-psk' : 'wpa2-psk';
          script += `add name="${secProfileName}" mode=dynamic-keys authentication-types="${authTypes}" wpa2-pre-shared-key="${config.password}" ${config.security === 'wpa2-wpa3-psk' ? `wpa3-pre-shared-key="${config.password}"` : ''}\n`;
        }
        script += `/interface wireless\n`;
        script += `set [ find default-name="${portName}" ] mode=ap-bridge ssid="${config.ssid}" security-profile="${secProfileName}" disabled=no ${config.band ? `band="${config.band}"` : ''}\n`;
        script += `/interface bridge port add bridge=${bridgeName} interface=${portName} comment="WLAN Port"\n`;
      });
    }

    // --- 7. DNS & FIREWALL ---
    script += `\n# --- DNS & Firewall ---\n`;
    script += `/ip dns set servers=${dnsConfig.servers.join(',')} allow-remote-requests=${dnsConfig.allowRemoteRequests ? 'yes' : 'no'}\n`;
    script += `/ip firewall nat add chain=srcnat action=masquerade out-interface-list=WAN comment="WAN Masquerade"\n`;

    // --- 8. MANGLE & PBR ---
    if (pbrConfig.enabled) {
      script += `\n# --- Policy Based Routing (PBR) ---\n`;
      script += `/ip firewall mangle\n`;
      script += `add chain=prerouting src-address-list=Local_Networks dst-address-list=Local_Networks action=accept comment="Bypass PBR for Local Traffic"\n`;
      networks.forEach(net => {
        const selectedWanId = pbrConfig.mappings[net.id];
        if (selectedWanId) {
           const wanIndex = wanList.findIndex(w => String(w.id) === String(selectedWanId)) + 1;
           if (wanIndex > 0) {
              const networkAddr = net.ip.replace('1/24', '0/24');
              script += `add chain=prerouting src-address=${networkAddr} dst-address-list=!Local_Networks action=mark-routing new-routing-mark=to_wan${wanIndex} passthrough=yes comment="Route ${net.name} -> WAN${wanIndex}"\n`;
           }
        }
      });
      wanList.forEach((wan, index) => {
          const i = index + 1;
          const gw = wan.type === 'pppoe' ? `pppoe-out${i}` : wan.gateway;
          script += `/ip route add distance=1 gateway=${gw} routing-mark=to_wan${i} comment="Route for WAN${i}"\n`;
      });
    }

    // --- 9. SYSTEM MONITORING & HEARTBEAT ---
    script += `\n################################################\n`;
    script += `# Monitoring & Heartbeat System\n`;
    script += `################################################\n`;
    
    script += `/system script remove [find name="heartbeat-script"]\n`;
    script += `/system script add name="heartbeat-script" source={\n`;
    script += `  :local serverUrl "${finalApiUrl}";\n`; // ✅ เปลี่ยนเป็น URL ที่คำนวณตาม Env
    script += `  :local apiToken "${token}";\n`;
    script += `  :local cpuLoad [/system resource get cpu-load];\n`;
    script += `  :local freeMem [/system resource get free-memory];\n`;
    script += `  :local totalMem [/system resource get total-memory];\n`;
    script += `  :local usedMem ($totalMem - $freeMem);\n`;
    script += `  :local memPercent (($usedMem * 100) / $totalMem);\n`;
    script += `  :local uptime [/system resource get uptime];\n`;
    script += `  :local version [/system resource get version];\n`;
    script += `  :local boardName [/system resource get board-name];\n`;
    script += `  :local freeHdd [/system resource get free-hdd-space];\n`;
    script += `  :local totalHdd [/system resource get total-hdd-space];\n`;
    script += `  :local hddPercent 0;\n`;
    script += `  :if ($totalHdd > 0) do={ :set hddPercent (((($totalHdd - $freeHdd) * 100) / $totalHdd)) };\n`;
    script += `  :local temp "N/A";\n`;
    script += `  :do {\n`;
    script += `    :local runTemp [:parse "/system health get [find name=\\"temperature\\"] value"];\n`;
    script += `    :set temp [$runTemp];\n`;
    script += `  } on-error={};\n`;
    script += `  :local latency "timeout";\n`;
    script += `  :do { :set latency ([:tostr ([/ping 8.8.8.8 count=1 as-value]->"time")]) } on-error={};\n`;
    script += `  :local payload "{\\"cpu\\":\\"$cpuLoad\\", \\"ram\\":\\"$memPercent\\", \\"storage\\":\\"$hddPercent\\", \\"temp\\":\\"$temp\\", \\"latency\\":\\"$latency\\", \\"uptime\\":\\"$uptime\\", \\"version\\":\\"$version\\", \\"boardName\\":\\"$boardName\\"}";\n`;    
    script += `  :do {\n`;
    // ✅ นำ Parameter ที่คำนวณไว้มาใส่ (เอา mode=http ออก และเพิ่ม check-certificate ตามเงื่อนไข)
    script += `    /tool fetch url=$serverUrl http-method=post http-header-field="Authorization: Bearer $apiToken,Content-Type: application/json" http-data=$payload keep-result=no ${fetchExtras};\n`;
    script += `  } on-error={ :log error "Failed to send Heartbeat" }\n`;
    script += `}\n`;

    script += `/system scheduler remove [find name="heartbeat-schedule"]\n`;
    script += `/system scheduler add name="heartbeat-schedule" interval=30s on-event="heartbeat-script"\n`;

    return script;

  } catch (error) {
    console.error("Generator Error:", error);
    return `# Error generating script: ${error.message}`;
  }
};